allowBuilds:
  '@parcel/watcher': false
  browser-tabs-lock: false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  textarea-selection-bounds: false
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2003.35'
  - '@angular-devkit/build-angular@20.3.35'
  - '@angular-devkit/build-webpack@0.2003.35'
  - '@angular-devkit/core@20.3.35'
  - '@angular-devkit/schematics@20.3.35'
  - '@angular/build@20.3.35'
  - '@angular/cli@20.3.35'
  - '@angular/ssr@20.3.35'
  - '@ngtools/webpack@20.3.35'
  - '@schematics/angular@20.3.35'
  - '@angular-devkit/architect@0.2102.22'
  - '@angular-devkit/core@21.2.22'
  - '@angular-devkit/schematics@21.2.22'
  - '@angular/build@21.2.22'
  - '@angular/cli@21.2.22'
  - '@angular/ssr@21.2.22'
  - '@schematics/angular@21.2.22'
