/**
 * Generates `src/icons.generated.scss` from the Tabler icon set.
 *
 * Each icon becomes a `.i-tabler-<name>` class sized `1em` and painted with
 * `currentColor` via `mask-image`, so icons inherit font-size and color the
 * same way the old Font Awesome glyphs did.
 *
 * Run `pnpm icons:gen` after changing ICONS below, and commit the result.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { getIconsCSS } from '@iconify/utils';

// Every icon the app uses. Keep sorted.
const ICONS = [
  'arrow-left',
  'arrow-right',
  'brush',
  'check',
  'clock',
  'cursor-text',
  'device-floppy',
  'eraser',
  'file-download',
  'folder-down',
  'help',
  'home',
  'lock',
  'map-pin',
  'pencil',
  'repeat',
  'settings',
  'square-check',
  'stack',
  'ticket',
  'trash-x',
  'x',
];

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const setPath = path.join(appRoot, 'node_modules/@iconify-json/tabler/icons.json');
const outPath = path.join(appRoot, 'src/icons.generated.scss');

const iconSet = JSON.parse(readFileSync(setPath, 'utf8'));

const missing = ICONS.filter(name => !iconSet.icons[name] && !iconSet.aliases?.[name]);
if (missing.length > 0) {
  throw new Error(`Not in the Tabler set: ${missing.join(', ')}`);
}

const css = getIconsCSS(iconSet, ICONS, { iconSelector: '.i-tabler-{name}' });

const header = [
  '// GENERATED by tools/icons-gen.mjs — do not edit.',
  '// Add or remove icons in that script, then run `pnpm icons:gen`.',
  '',
].join('\n');

writeFileSync(outPath, header + css, 'utf8');
console.log(`Wrote ${ICONS.length} icons to ${path.relative(appRoot, outPath)}`);
